

server:
  port: 9430


spring:
  application:
    name: api-gateway
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间
  cloud:
    gateway:
      routes:
        - id: DouyinUSerService
          uri: lb://DouyinUSerService
          predicates:
            - Path=/user/**
#          filters:
#            - RewritePath=/user/(?<segment>.*), /user/${segment}
        - id: DouyinIntroduceService
          uri: lb://DouyinIntroduceService
          predicates:
            - Path=/introduce/**
        - id: DouyinVideoService
          uri: lb://DouyinVideoService
          predicates:
            - Path=/video/**
        - id: DouyinAdminService
          uri: lb://DouyinAdminService
          predicates:
            - Path=/admin/**
        - id: DouyinMusicService
          uri: lb://DouyinMusicService
          predicates:
            - Path=/music/**
        - id: DouyinCommentService
          uri: lb://DouyinCommentService
          predicates:
            - Path=/comment/**
        - id: DouyinChatService
          uri: lb://DouyinChatService
          predicates:
            - Path=/chat/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  # Eureka服务器地址
