#
#spring:
#
#  application:
#    name: DouyinFileService
#  datasource:
#    username: root
#    password: root
#    url: jdbc:mysql://localhost:3306/douyintest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
#  freemarker:
#    cache: false  #关闭模板缓存，方便测试
#    settings:
#      template_update_delay: 0 #检查模板更新延迟时间，设置为0表示立即检查，如果时间大于0会有缓存不方便进行模板测试
#    suffix: .ftl
#server:
#  port: 9015
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
#
#minio:
#  accessKey: minio
#  secretKey: minio123
#  bucket: good
#  endpoint: http://192.168.200.130:9000
#  readPath: http://192.168.200.130:9000

server:
  port: 8090


spring:
  application:
    # 应用的名称，可选
    name: DouyinArticleService  # 设置应用名称为 DouyinUserService
  datasource:
    url: jdbc:mysql://localhost:3306/douyinComment?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    # 开发环境密码
    password: root