

server:
  port: 9430


spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: DouyinUserService
          uri: lb://DouyinUserService
          predicates:
            - Path=/user/**
        - id: DouyinVideoService
          uri: lb://DouyinVideoService
          predicates:
            - Path=/video/**
        - id: DouyinAdminService
          uri: lb://DouyinAdminService
          predicates:
            - Path=/admin/**
        - id: DouyinVideoService
          uri: lb://DouyinVideoService
          predicates:
            - Path=/music/**
        - id: DouyinCommentService
          uri: lb://DouyinCommentService
          predicates:
            - Path=/comment/**
        - id: DouyinChatService
          uri: lb://DouyinChatService
          predicates:
            - Path=/chat/**
        - id: DouyinShopService
          uri: lb://DouyinShopService
          predicates:
            - Path=/shop/**

      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  # Eureka服务器地址
