spring:

  rabbitmq:
    host: 192.168.200.130  # RabbitMQ 服务器的主机地址
    port: 5672  # RabbitMQ 服务器的端口号
    username: itcast  # RabbitMQ 的用户名
    password: 123321  # RabbitMQ 的密码
    virtual-host: /  # RabbitMQ 的虚拟主机

  application:
    #应用的名称，可选
    name: DouyinShopService
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/douyintest?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false




# Sa-Token 配置
sa-token:
  # SSO-相关配置
  sso-client:
    # SSO-Server端主机地址
    server-url: http://127.0.0.1:8988

  # 配置 Sa-Token 单独使用的Redis连接 （此处需要和SSO-Server端连接同一个Redis）
  alone-redis:
    # Redis数据库索引
    database: 1
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # 连接超时时间
    timeout: 10s


eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka  # Eureka服务器地址

minio:
  accessKey: minio
  secretKey: minio123
  bucket: leadnews
  endpoint: http://192.168.200.130:9000
  readPath: http://192.168.200.130:9000
